/** 라우트 경로의 Single Source. 하드코딩된 경로 문자열 사용 금지. */
export const ROUTES = {
  home: "/",
  login: "/login",
  signup: "/signup",
  search: "/search",
  sermons: "/sermons",
  sermonDetail: (id: string) => `/sermons/${id}`,
  sermonNew: "/sermons/new",
  sermonEdit: (id: string) => `/sermons/${id}/edit`,
  migration: "/migration",
  testimonies: "/testimonies",
  testimonyDetail: (id: string) => `/testimonies/${id}`,
  testimonyNew: "/testimonies/new",
  testimonyEdit: (id: string) => `/testimonies/${id}/edit`,
  pastorApply: "/pastor/apply",
  pastorPage: (username: string) => `/@${username}`,
  archive: "/archive",
  bookmarks: "/bookmarks",
  seeds: "/seeds",
  admin: "/admin",
  adminPastors: "/admin/pastors",
  adminReports: "/admin/reports",
  adminContents: "/admin/contents",
  adminSeeds: "/admin/seeds",
  adminCuration: "/admin/curation",
} as const;
